/*******************************************************************************************
*
* ©2016 Symbol Technologies LLC. All rights reserved.
*
********************************************************************************************/
#if !defined(AFX_SCANNER_H__6552FB04_D096_49D4_8824_1C42B2957353__INCLUDED_)
#define AFX_SCANNER_H__6552FB04_D096_49D4_8824_1C42B2957353__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CScanner wrapper class

class CScanner : public CWnd
{
protected:
	DECLARE_DYNCREATE(CScanner)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x27d61a3, 0x4251, 0x11d0, { 0xb7, 0xa4, 0x80, 0xbb, 0xff, 0xc0, 0x0, 0x0 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	CString GetCheckHealthText();
	void SetCheckHealthText(LPCTSTR);
	BOOL GetClaimed();
	void SetClaimed(BOOL);
	BOOL GetDataEventEnabled();
	void SetDataEventEnabled(BOOL);
	BOOL GetDeviceEnabled();
	void SetDeviceEnabled(BOOL);
	BOOL GetFreezeEvents();
	void SetFreezeEvents(BOOL);
	long GetOutputID();
	void SetOutputID(long);
	long GetResultCode();
	void SetResultCode(long);
	long GetResultCodeExtended();
	void SetResultCodeExtended(long);
	long GetState();
	void SetState(long);
	CString GetControlObjectDescription();
	void SetControlObjectDescription(LPCTSTR);
	long GetControlObjectVersion();
	void SetControlObjectVersion(long);
	CString GetServiceObjectDescription();
	void SetServiceObjectDescription(LPCTSTR);
	long GetServiceObjectVersion();
	void SetServiceObjectVersion(long);
	CString GetDeviceDescription();
	void SetDeviceDescription(LPCTSTR);
	CString GetDeviceName();
	void SetDeviceName(LPCTSTR);
	CString GetScanData();
	void SetScanData(LPCTSTR);
	BOOL GetAutoDisable();
	void SetAutoDisable(BOOL);
	long GetBinaryConversion();
	void SetBinaryConversion(long);
	long GetCapPowerReporting();
	void SetCapPowerReporting(long);
	long GetDataCount();
	void SetDataCount(long);
	long GetPowerNotify();
	void SetPowerNotify(long);
	long GetPowerState();
	void SetPowerState(long);
	BOOL GetDecodeData();
	void SetDecodeData(BOOL);
	CString GetScanDataLabel();
	void SetScanDataLabel(LPCTSTR);
	long GetScanDataType();
	void SetScanDataType(long);
	long GetOpenResult();
	void SetOpenResult(long);

// Operations
public:
	long Open(LPCTSTR lpszDeviceName);
	long Close();
	long Claim(long lTimeout);
	long Release();
	long ClearInput();
	long ClearOutput();
	long DirectIO(long lCommand, long* plData, BSTR* pstrString);
	long CheckHealth(long lLevel);
	long ClaimDevice(long lTimeout);
	long ReleaseDevice();
	long CloseDevice();
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SCANNER_H__6552FB04_D096_49D4_8824_1C42B2957353__INCLUDED_)
